name = "Zapf"
license = "MIT"
licenselink = "https://github.com/guemax/zapf/blob/main/LICENSE"
description = "A Hugo theme for fans of Hermann Zapf."

homepage = "https://github.com/guemax/zapf"
demosite = "https://guemax.de"

tags = ["responsive", "simple", "clean", "light", "dark", "blog", "minimal"]

features = [
    "responsive",
    "blog",
    "table-of-contents",
    "highlight.js",
    "favicon",
    "social-icons",
    "minified-assets",
    "dark-light-images",
]

[author]
name = "Max Günther"
homepage = "https://guemax.de"

[original]
name = "Francesco Tomaselli"
homepage = "https://tomfran.github.io/"
